=== astro/libxml-ruby/libxslt/tests/commentary.dtd
<!ELEMENT commentary (meta, body)>
<!ELEMENT meta (author, version, date, id, title, subtitle?)>

<!-- Metadata about the requirements -->
<!ENTITY % string       "#PCDATA">
<!ENTITY % character    "#PCDATA">
<!ENTITY % letter       "#PCDATA">
<!ENTITY % number_att   "CDATA">


<!ELEMENT author (first_name, last_name, email)>

<!ELEMENT first_name   (%string;)>
<!ELEMENT last_name    (%string;)>
<!ELEMENT email        (%string;)>

<!ELEMENT version       (#PCDATA)>
<!ELEMENT date          (#PCDATA)>
<!ELEMENT id            (#PCDATA)>
<!ELEMENT title         (#PCDATA)>
<!ELEMENT subtitle      (#PCDATA)>

<!ELEMENT body (para+)>


<!ELEMENT para (#PCDATA|thought|url|ol)*>
<!ATTLIST para
          style     (default|ps) "default">

<!ELEMENT ol      (li+)>
<!ELEMENT li      (#PCDATA)>
<!ELEMENT url     (#PCDATA)>
<!ELEMENT thought (#PCDATA)>

=== astro/libxml-ruby/libxslt/tests/fuzface.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="fuzface.xsl" type="text/xsl"?>

<!DOCTYPE commentary SYSTEM "commentary.dtd">

<commentary>
  <meta>
    <author>
      <first_name>Sean</first_name>
      <last_name>Chittenden</last_name>
      <email>sean@chittenden.org</email>
    </author>
    <version>$Version$</version>
    <date>$Date$</date>
    <id>$Id$</id>
    <title>Fuzface...</title>
    <subtitle>The Internet's a big place and here's some proof...</subtitle>
  </meta>

  <body>
    <para>
      I think it's a tragedy that I'm going to start off my new
      commentary by talking about facial hair and the Internet.
      Something about that just screams pathetic, but whatever: it's
      humor and that's life.
    </para>

    <para>
      I've been working at home for a while now, which has been great.
      I've been doing a lot of reading, good work, contributing to the
      FreeBSD project, and living life at my own pace.  The problem?
      I don't have to interact with people, so I've let my appearance
      slide a bit, most notably I've gone two weeks without shaving
      and I have an awful hairy face.
    </para>

    <para>
      Nothing is worse than going for a hard run, coming back, and
      then bending your head down so that the hairs under your chin
      touch the hairs on your neck.  This has to be one of the most
      disgusting/gross feelings I've experienced in a while.  While
      today wasn't the first time I'd experienced such a slimy tangled
      mess, it is the first time I seriously considered shaving part
      of my face, but not all of it: I was considering a beard.
    </para>

    <para>
      Alright, so it's 5pm and I'm a sweaty post-run mess (it was 110
      degrees in direct sunlight according to my thermometer) and
      considering the possibility of growing a beard.  Swifty nift?
      Maybe.  This is something I'd never done before, let alone
      seriously consider.  Normally I'd call my dad for such manly
      advice, but he is: a) normally in another state, and; b) in
      another country right now probably growing a beard (he's
      notorious for coming back from a trip with a gnarly unshaven
      face, sometimes he'll shape it into a decent beard).  So, what's
      a tech-junkie to do?  Hop on the Internet and see if Google's
      able to provide me with some inspiration.
    </para>

    <para>
      Sure enough, I typed in "pictures of bearded men" and I was able
      to find something: 14,000 pages of something to be exact.
      Anyway, so most of these were rinky dink sites, a few of them
      had some promise.  One guy was trying to start a tradition where
      everyone grows a beard for New Years.  As I was scrolling down
      the page trying to find some pictures, my mind was having the
      following thought process: <thought>This seems like a dumb
      idea... New Years provides a perfectly good excuse to kiss some
      total stranger that you've had your eye on for the duration of a
      New Years party.  Why waste such an opportunity with a crappy
      kiss?</thought> And at about this point I said this page sucks,
      and flipped back to my search results.
    </para>

    <para>
      Since I'd never done this before, I didn't know what was
      fashionably correct in terms of where a guy should shave under
      his neck, or what the deal was...  I knew there were lots of
      styles out there, just none that I could picture in my mind
      (save maybe Santa Claus and a few really gnarly beards that are
      long enough to be used as full-body covering.  Oooh!  And don't
      forget the Russian and Amish beards, those stand out in my mind
      too.).  Google, being pretty comprehensive, and the Internet
      being huge, found the exact screwball page I was looking for:
      <url>http://fuzface-gallery.tripod.com/</url>
    </para>

    <para>
      I don't know if I really should be amazed at the sheer number of
      entries that Google returned, or that the Internet is big enough
      to house such random gallery of crap, but it is and it never
      ceases to amaze me...  it's almost as amazing as the fact that
      some bozo spent the time to create such a page.  Don't people
      have lives?  Oh wait, I just visited his page...  so back to my
      diatribe...
    </para>

    <para>
      There were tons of faces, lots of men, lots of hair, and plenty
      of styles to choose from.  Page after page of faces and hair.
      Ugh.  This wasn't getting any where and I was now entertaining
      the rebound though of shaving my head.  Time to close my browser
      and hop in the shower: I reak.  So what'd I do?  Well, after
      looking through enough of those pictures, I decided a few
      things:
    </para>

    <para>
      <ol>
        <li>
	  I'm amazed that the Internet is big enough to foster the
	  creation of such random and utterly useless information.  Then
	  again, I've been on and using the Net since '95, so this
	  shouldn't surprise me that much.
        </li>

        <li>
          There are a lot of guys out there with varying tastes in,
	  shall we say, "facial hair styles," most of which I find
	  pretty unappealing.
        </li>

        <li>
	  I don't like beards.  After one clogged drain, two
	  reapplications of shaving cream, and a few pases with the
	  razor, it took me about 5-10 minutes to get a nice cleanly
	  shaven face.
        </li>

        <li>
          &lt;crass comment&gt;And - back me up here fellas, you can
	  sympathize with this feeling after you get done looking
	  through a magazine for a hair-cut style (ladies.. just smile
	  and nod and pretend you care) - after looking at a few dozen
	  pictures of men, I was able to safely reaffirm my desire for
	  heterosexual relations (translation from Bill Clintonese: have
	  sex with a woman).  And with that thought in mind, I began to
	  pine for the college porn collection of old.  Mmmm,
	  Playboy.&lt;/crass comment&gt;
        </li>
      </ol>
    </para>

    <para>
      ::grin::  Until next time.  -Sean
    </para>

    <para style="ps">
      P.S.  To the guys out there with beards, this is just my
      opinion: take it with a grain of salt.
    </para>
  </body>
</commentary>
