=== astro/libxml-ruby/test/model/sdef.dtd
<!-- BASICS -->
<!ENTITY % Typename "NMTOKENS">
<!ENTITY % Classname "NMTOKENS">
<!ENTITY % EventCode "CDATA">
<!ENTITY % OSType "CDATA">
<!ENTITY % Term "NMTOKENS">
<!ENTITY % Text "CDATA">
<!ENTITY % Verbname "NMTOKENS">

<!ENTITY % yorn "(yes | no)">

<!-- DICTIONARY (ROOT ELEMENT) -->
<!ELEMENT dictionary (documentation*, suite+)>
<!ATTLIST dictionary
  title      CDATA           #IMPLIED 
  >

<!-- DOCUMENTATION ELEMENTS -->
<!ELEMENT documentation (html*)>
<!ELEMENT html (#PCDATA)>

<!ELEMENT xref EMPTY>
<!ATTLIST xref
  target     CDATA           #REQUIRED
  hidden     %yorn;          #IMPLIED 
  >

<!-- IMPLEMENTATION ELEMENTS -->
<!ENTITY % implementation "(cocoa)">
<!ELEMENT cocoa EMPTY>
<!ATTLIST cocoa
  name       NMTOKEN         #IMPLIED
  class      NMTOKEN         #IMPLIED
  key        NMTOKEN         #IMPLIED
  method     NMTOKEN         #IMPLIED
  insert-at-beginning %yorn; #IMPLIED
  boolean-value (YES|NO)     #IMPLIED
  integer-value NMTOKEN      #IMPLIED
  string-value  CDATA        #IMPLIED
  >

<!-- SUITES -->
<!ELEMENT suite ((%implementation;)?, (class | class-extension | command | documentation | enumeration | event | record-type | value-type)+)>
<!ATTLIST suite
  name       CDATA           #REQUIRED
  code       %OSType;        #REQUIRED 
  description  %Text;        #IMPLIED
  hidden     %yorn;          #IMPLIED 
  >

<!-- SYNONYMS -->
<!ELEMENT synonym ((%implementation;)?)>
<!ATTLIST synonym
  name       %Term;          #IMPLIED
  code       %OSType;		 #IMPLIED
  hidden     %yorn;          #IMPLIED 
  >
  <!-- at least one of "name" and "code" is required. -->

<!-- TYPES -->
<!ELEMENT type EMPTY>
<!ATTLIST type
  type       %Typename;      #REQUIRED 
  list       %yorn;          #IMPLIED
  hidden     %yorn;          #IMPLIED 
  >

<!-- VERBS (COMMANDS OR EVENTS) -->
<!ELEMENT command ((%implementation;)?, synonym*, direct-parameter?, parameter*, result?, documentation*, xref*)>
<!ATTLIST command
  name       %Verbname;      #REQUIRED
  id         ID              #IMPLIED
  code       %EventCode;     #REQUIRED 
  description  %Text;        #IMPLIED
  hidden     %yorn;          #IMPLIED 
  >

<!ELEMENT event ((%implementation;)?, synonym*, documentation*, direct-parameter?, (documentation | parameter)*, result?, documentation*, xref*)>
<!ATTLIST event
  name       %Verbname;      #REQUIRED
  id         ID              #IMPLIED
  code       %EventCode;     #REQUIRED 
  description  %Text;        #IMPLIED
  hidden     %yorn;          #IMPLIED 
  >

<!ELEMENT direct-parameter (type*)>
<!ATTLIST direct-parameter
  type       %Typename;      #IMPLIED 
  optional   %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!ELEMENT result (type*)>
<!ATTLIST result
  type       %Typename;      #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!ELEMENT parameter ((%implementation;)?, (type*))>
<!ATTLIST parameter
  name       %Term;          #REQUIRED
  code       %OSType;        #REQUIRED 
  hidden     %yorn;          #IMPLIED 
  type       %Typename;      #IMPLIED 
  optional   %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!-- CLASSES -->
<!ENTITY % class-contents "(contents | documentation | element | property | responds-to | synonym | xref)">
<!ELEMENT class ((%implementation;)?, (%class-contents;)*)>
	<!-- not quite accurate; there can be at most one contents element. -->
<!ATTLIST class
  name       %Term;          #REQUIRED
  id         ID              #IMPLIED
  code       %OSType;        #REQUIRED 
  hidden     %yorn;          #IMPLIED 
  plural     %Term;          #IMPLIED 
  inherits   %Classname;     #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!-- contents -->
<!ELEMENT contents ((%implementation;)?, (type*))>
<!ATTLIST contents
  name       %Term;          #IMPLIED
  code       %OSType;        #IMPLIED 
  type       %Typename;      #IMPLIED
  access     (r | w | rw)    "rw"     
  hidden     %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!-- element access -->
<!ELEMENT element ((%implementation;)?, accessor*)>
<!ATTLIST element
  type       %Typename;      #REQUIRED
  access     (r | w | rw)    "rw"     
  hidden     %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!ENTITY % accessor-type "(index | name | id | range | relative | test)">
<!ELEMENT accessor EMPTY>
<!ATTLIST accessor
  style      %accessor-type;  #REQUIRED
  >

<!-- properties -->
<!ELEMENT property ((%implementation;)?, (type | synonym | documentation)*)>
<!ATTLIST property
  name       %Term;          #REQUIRED
  code       %OSType;        #REQUIRED 
  hidden     %yorn;          #IMPLIED 
  type       %Typename;      #IMPLIED 
  access     (r | w | rw)    "rw"     
  in-properties  %yorn;      #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!-- supported verbs -->
<!ELEMENT responds-to ((%implementation;)?)>
<!ATTLIST responds-to
  command    %Verbname;      #REQUIRED
  hidden     %yorn;          #IMPLIED 

  name       %Verbname;      #IMPLIED
  >
  <!-- "name" is now "command"; "name" is still defined for backward compatibility. -->

<!-- class extensions -->
<!ELEMENT class-extension ((%implementation;)?, (%class-contents;)*)>
<!ATTLIST class-extension
  extends    %Classname;     #REQUIRED
  hidden     %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >


<!-- SIMPLE TYPES -->

<!-- values -->
<!ELEMENT value-type ((%implementation;)?, synonym*, documentation*, xref*)>
<!ATTLIST value-type
  name       %Term;          #REQUIRED
  code       %OSType;        #REQUIRED 
  hidden     %yorn;          #IMPLIED 
  plural     %Term;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!-- records -->
<!ELEMENT record-type ((%implementation;)?, synonym*, (documentation | property | xref)+)>
	<!-- should be at least one property. -->
<!ATTLIST record-type
  name       %Term;          #REQUIRED
  code       %OSType;        #REQUIRED 
  hidden     %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

<!-- enumerations -->
<!ELEMENT enumeration ((%implementation;)?, (documentation | enumerator | xref)+)>
	<!-- should be at least one enumerator. -->
<!ATTLIST enumeration
  name       %Term;          #REQUIRED
  code       %OSType;        #REQUIRED
  hidden     %yorn;          #IMPLIED
  description  %Text;        #IMPLIED
  inline     CDATA           #IMPLIED
  >

<!ELEMENT enumerator ((%implementation;)?, synonym*, documentation*)>
<!ATTLIST enumerator
  name       %Term;          #REQUIRED
  code       %OSType;        #REQUIRED 
  hidden     %yorn;          #IMPLIED 
  description  %Text;        #IMPLIED 
  >

=== astro/libxml-ruby/test/model/itunes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "sdef.dtd">
<dictionary>
  <suite name="Standard Suite" code="****" description="Common terms for most applications">
    <class name="application" code="capp" description="The application program">
      <property name="current encoder" code="pEnc" type="encoder" description="the currently selected encoder (MP3, AIFF, WAV, etc.)"/>
      <property name="current EQ preset" code="pEQP" type="EQ preset" description="the currently selected equalizer preset"/>
      <property name="current playlist" code="pPla" type="playlist" access="r" description="the playlist containing the currently targeted track"/>
      <property name="current stream title" code="pStT" type="text" access="r" description="the name of the current song in the playing stream (provided by streaming server)"/>
      <property name="current stream URL" code="pStU" type="text" access="r" description="the URL of the playing stream or streaming web site (provided by streaming server)"/>
      <property name="current track" code="pTrk" type="track" access="r" description="the current targeted track"/>
      <property name="current visual" code="pVis" type="visual" description=" the currently selected visual plug-in"/>
      <property name="EQ enabled" code="pEQ " type="boolean" description="is the equalizer enabled?"/>
      <property name="fixed indexing" code="pFix" type="boolean" description="true if all AppleScript track indices should be independent of the play order of the owning playlist."/>
      <property name="frontmost" code="pisf" type="boolean" description="is iTunes the frontmost application?"/>
      <property name="full screen" code="pFSc" type="boolean" description="are visuals displayed using the entire screen?"/>
      <property name="name" code="pnam" type="text" access="r" description="the name of the application"/>
      <property name="mute" code="pMut" type="boolean" description="has the sound output been muted?"/>
      <property name="player position" code="pPos" type="integer" description="the playerâ€™s position within the currently playing track in seconds."/>
      <property name="player state" code="pPlS" type="ePlS" access="r" description="is iTunes stopped, paused, or playing?"/>
      <property name="selection" code="sele" type="specifier" access="r" description="the selection visible to the user"/>
      <property name="sound volume" code="pVol" type="integer" description="the sound output volume (0 = minimum, 100 = maximum)"/>
      <property name="version" code="vers" type="version" access="r" description="the version of iTunes"/>
      <property name="visuals enabled" code="pVsE" type="boolean" description="are visuals currently being displayed?"/>
      <property name="visual size" code="pVSz" type="eVSz" description="the size of the displayed visual"/>
    </class>
    <enumeration name="eSrA" code="eSrA">
      <enumerator name="albums" code="kSrL" description="albums only"/>
      <enumerator name="all" code="kSrA" description="all text fields"/>
      <enumerator name="artists" code="kSrR" description="artists only"/>
      <enumerator name="composers" code="kSrC" description="composers only"/>
      <enumerator name="displayed" code="kSrV" description="visible text fields"/>
      <enumerator name="songs" code="kSrS" description="song names only"/>
    </enumeration>
  </suite>
</dictionary>
